[settings]
env_file = ".env"

[tools]
aws-sam-cli = "1.117.0"
awscli = "2.9.12"
fzf = "0.60.0"
gcloud = "500.0.0"
go = "1.24.4"
helm = "3.16.4"
k9s = "0.32.7"
krew = "0.4.3"
kubectl = "1.32.0"
kubent = "0.7.3"
neovim = "0.10.4"
nodejs = "22.13.0"
operator-sdk = "1.38.0"
pnpm = "9.15.4"
poetry = "1.6.1"
protoc = "3.18.1"
python = "3.11.5"
rclone = "1.64.0"
restic = "0.17.3"
ripgrep = "14.1.0"
stern = "1.31.0"
task = "3.28.0"
terraform = "1.4.2"
tree-sitter = "0.20.8"
vault = "1.13.0+ent"
zoxide = "0.9.7"
